// DEPLOY TEST v1.0.1 - 2025-12-22

const animeData = [
  {
    Title: "Charlotte",
    Genre: "Thriller / Supernatural",
    Rating: "9/10",
    image: "charlotte.png",
    Seasons: "1 season",
    Description: "A group of high school students with unstable supernatural abilities are brought together to prevent those powers from being exploited, only to uncover darker consequences tied to their existence.",
    Review: "I originally clicked on this anime because I thought it was going to be a cute romance story. Boy I was wrong.  It starts off as a lighthearted quicky school anime but quickly turns into a deep physiological bittersweet story. There is incredibly strong character development with the MC as the story progresses. Consequences are real and terribly harsh with the story getting increasingly intricate. Every character is well written and important to the overall story. The foreshadowing is clever and the title does serve a purpose. The only complaint I have about this anime is that the last episode was rushed for having such a good buildup.",
    Tags: ["existential-questions","drama","supernatural","juxtaposition","emotional"],
    Studio: "P.A. Works",
    Platforms: ["Crunchyroll","Netflix","Amazon Video","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/kU5tGma7LaU",
    Top10Rank: 8
  },
  {
    Title: "The Eminence in Shadow",
    Genre: "Isekai / Fantasy",
    Rating: "8.5/10",
    image: "eminence-in-shadow.png",
    Seasons: "2 seasons",
    Description: "A high school boy that dedicated his life to being the strongest meets an untimely end. He's given a second chance.",
    Review: "Great satire anime where the MC is totally unaware that everyone around him genuinely believes in his motivations and actions. While it's silly at times the goals of the MC are just as important to the anime and brought up consistently. The serious moments are great. Moonlight Sonada being the MCs theme is iconic and perfectly matches the tone of the anime. Smooth animation, devolved side characters. One of my personal favorites if not my favorite anime.",
    Tags: ["op-mc","comedy","action","power","absurd","secret-society","fan-service","aura-farming"],
    Studio: "Nexus",
    Platforms: ["DisneyPlus","Hulu","HIDIVE","Amazon Video","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/L7LgAbGF-WY",
    Top10Rank: 1
  },
  {
    Title: "Hell's Paradise",
    Genre: "Action / Supernatural",
    Rating: "10/10",
    image: "hells-paradise.png",
    Seasons: "2 seasons",
    Description: "An elite shinobi on death row is offered a pardon in exchange for finding the Elixir of Life on a mysterious island.",
    Review: "Superb animation, good storyline, and a fire score. This was one of those anime where you kinda take a step back and appreciate what greatness looks like. The motivations of the MC are incredibly thought out and yet there's more than what meets the eye (spoilers). Fight choreography was incredible and the world building was also superb. One of my favorites.",
    Tags: ["action","ninja","redemption","immortality","human-nature","ost","combat"],
    Studio: "MAPPA",
    Platforms: ["Crunchyroll","Netflix","Hulu","Amazon Video","hianime","9anime"],
    Trailer: "https://www.youtube.com/embed/aaHZdwPZX6g",
    Top10Rank: 7
  },
  {
    Title: "Attack on Titan",
    Genre: "Mystery / Psychological",
    Rating: "15/10",
    image: "attack-on-titan.png",
    Seasons: "4 seasons, 1 movie",
    Description: "A boy wants to kill every titan after the death of his mom.",
    Review: "This is one of my favorite animes. I personally believe that this is the greatest storyline/plot of all time. The amount of foreshadowing is actually insane when you watch it a 2nd - 5th time. The writing of the characters is some of the best I have ever seen. Genuinely pulling some of the greatest questions and perspectives out of each character. The score is something else on its own. It's out of this world. As for the writing, I don't think there was a single plot hole left in this anime.The sheer amount of detail in the world building and titan descriptions is utterly insane. I'm 100% a glazer of this anime but objectively this is one of the most well written animes in history.",
    Tags: ["action","psychological","war-and-freedom","identity","emotional","animation"],
    Studio: "Wit Studio & MAPPA",
    Platforms: ["Crunchyroll","Hulu","Amazon Video","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/n4Nj6Y_SNYI",
    Top10Rank: 3
  },
  {
    Title: "The Angel Next Door Spoils Me Rotten",
    Genre: "Romance / Slice of Life",
    Rating: "10/10",
    image: "angel-next-door.png",
    Seasons: "1 season",
    Description: "A boy offers his umbrella to a girl sitting in the rain",
    Review: "My all-time favorite romance anime. A perfect setting and start leads to the most wholesome and sweet interactions in anime. Whenever I think of this story I genuinely start smiling and kicking my feet. The story is able to be interesting with realistic plot points and emotions. The side characters also exist and aren't just forgotten the anime always has its focus on the two main characters.  Not to mention and completely unique premise I haven't seen in a romance anime before. When it comes to feel goods, it's hard to beat this.",
    Tags: ["school","romcom","wholesome","caring","personal-growth"],
    Studio: "Project No. 9",
    Platforms: ["Crunchyroll","Amazon Prime Video","Apple TV+","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/twfLsWdXcZI",
    Top10Rank: 4
  },
  {
    Title: "Re:ZERO - Starting Life in Another World",
    Genre: "Isekai / Fantasy",
    Rating: "10/10",
    image: "re-zero.png",
    Seasons: "3 seasons, 2 specials",
    Description: "A shut-in teenager is suddenly transported to a fantasy world where nothing is as kind as it first appears. Armed with a mysterious secret ability, he must navigate a dangerous world while trying to protect the people he grows close to.",
    Review: "When it comes to the greatest isekai anime. Re:ZERO is always in the conversation of having the best story and original adaptation. With that being said, one of the reasons the story is so good is because of how tragic it can be. The episodes are long, brutal, and showcase many emotional struggles. The MC is constantly beaten to the ground and yet, figures out a way to always find the strength to keep moving forward. There are occasional slow moments but overall, the story is immaculate. This isekai is unique to the hundreds of slop stories since the MC is never overpowered at any point in the story. It's his intelligence and use of what's given to him that make him so deadly. The anime teaches lessons most don't dare approach.",
    Tags: ["thriller","fantasy","magic","resilience","trauma","loyalty","dark","action"],
    Studio: "White Fox",
    Platforms: ["Crunchyroll","Hulu","Apple TV+","Amazon Video","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/Slz_rahWp6Y",
    Top10Rank: 2
  },
  {
    Title: "Call of the Night",
    Genre: "Supernatural / Romance",
    Rating: "10/10",
    image: "call-of-the-night.png",
    Seasons: "2 seasons",
    Description: "A disillusioned boy wanders around the streets alone at night in search of meaning and stumbles upon an interesting girl with seveal secrets.",
    Review: "The stunning backgrounds and atmospheric artworks blew me away. This is genuinely one of the most gorgeous looking anime iv seems. Main characters are fantastic and the show balances some goofy charm with surprisingly deep and introspective themes around love and connection. Easy to binge, wholesome with a touch of action. The gorgeous and vibrant visuals alone sets this one apart from the rest. One of my personal favorites.",
    Tags: ["vampires","late-night","slowburn","atmospheric","visuals","nightlife","romcom"],
    Studio: "LIDENFILMS",
    Platforms: ["HIDIVE","Disney Plus","Apple TV+","Amazon Video","Hulu","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/Dds5rvJEYN8JIz9U",
    Top10Rank: 5
  },
  {
    Title: "Demon Slayer",
    Genre: "Shonen / Action",
    Rating: "9/10",
    image: "demon-slayer.png",
    Seasons: "5 seasons, 1 movie",
    Description: "A boy joins the Demon Slayer Corps after his family is slaughtered and his sister is turned into a demon vowing to restore her to a human.",
    Review: "Unbelievable animation. The story arcs are incredibly well done. All characters are given due justice over time (yes, even zenitsu) and the world lore is well done. People shit on this anime for just being quote on quote eye candy but there is clear character progression, well told emotional backstories that influence the story, power systems, and characters actually get killed off. Yeah the animation is great and i'm not denying that but theres more than JUST animation. I think this is a classic case of an anime that got too popular so its gets hated on. Solid watch from me.",
    Tags: ["swords","action","good-characters","animation","visuals","epic-battles","revenge"],
    Studio: "Ufotable",
    Platforms: ["Netflix","Crunchyroll","Amazon Video","Hulu","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/wPFeBxt7VXI"
  },
  {
    Title: "One Punch Man",
    Genre: "Shonen / Action",
    Rating: "7/10",
    image: "one-punch-man.png",
    Seasons: "2 seasons, specials",
    Description: "A hero so powerful he defeats any enemy in a single punch struggles with the boredom of invincibility.",
    Review: "Definition of falling from glory. The anime is at its core an ironic comedy since the MC cannot lose a fight, so it focuses on the other struggles he has. A very unique premise where they balance out that storyline with intricate side characters who are thoroughly written and explored. Animation was also insane for the first 2 seasons. There are times when the fan service is heavy but bear with it. The anime knows to create a meaningful and powerful story even when the entire premise is ultimately around a character that’s too strong for any battle. Unfortunately, perfection comes at a cost. Season 3 did not deliver anything close to the quality and authenticity of the first two seasons. It’s sad but we can hope it one day gets revived. Mind you, the first two seasons are amazing but that third season is what brings the rating so low.",
    Tags: ["action","animation","comedy","fan-service","op-mc","epic-battles"],
    Studio: "Madhouse & J.C.Staff",
    Platforms: ["Amazon Video","Hulu","Netflix","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/Poo5lqoWSGw"
  },
  {
    Title: "Kaiju No. 8",
    Genre: "Shonen / Action",
    Rating: "9/10",
    image: "kaiju-no-8.png",
    Seasons: "2 seasons",
    Description: "In a world plagued by monstrous kaiju attacks, a middle-aged cleanup worker unexpectedly gains the ability to transform into a kaiju himself, forcing him to secretly pursue his dream of joining the elite defense force sworn to eradicate the very creatures he has become.",
    Review: "Few beat Kaiju. No 8 in consideration of goated animation and fight scenes. This anime features an awesome MC who you can't help but root for the entire way. Not only that but the side characters all have compelling stories and motivations. Season 2 continues after the cliff hanger of season 1 and continues building up the plot in powerful and decisive moments. The only thing that holds back this anime is following a generic shonen plot with a few cliches that are overdone. For sure one of the bigger modern anime titles.",
    Tags: ["action","animation","kaiju","military","op-mc","epic-battles","duty", "plot thickens", "fight-scenes"],
    Studio: "Production I.G",
    Platforms: ["Crunchyroll","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/JwF7bhvnCxI",
  },
  {
    Title: "Jujutsu Kaisen",
    Genre: "Shonen / Action",
    Rating: "10/10",
    image: "jjk.png",
    Seasons: "3 seasons, 1 movie",
    Description: "A high school student becomes host to a powerful curse and is drawn into the hidden world of jujutsu sorcerers, where he must fight deadly supernatural threats while struggling to retain his humanity.",
    Review: "One of the big 3 in modern anime and it absolutely delivers on that title. MAPPA studio delivers some of the most unbelievable animation paired with fight choreography that's out of this world. It's one of those rare cases where an anime can have such serious moments and important events while maintaining humorous and slice of life moments. There are so many characters that stand out and provide such an important role to the story that they simply take over the anime world. I guarantee that this show has had more of an impact on human culture than some actual real events happening today. It's that good. If you haven't watched this phenomenon show. Go watch it. Oh sorry did I not mention Gojo and toji? ",
    Tags: ["action","animation","intense","supernatural","curses","epic-battles","sorcery"],
    Studio: "MAPPA",
    Platforms: ["Crunchyroll","Netflix","Hulu","Amazon Prime Video","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/pkKu9hLT-t8",
    Top10Rank: 10
  },
  {
    Title: "Solo Leveling",
    Genre: "Shonen / Action",
    Rating: "9/10",
    image: "solo-leveling.png",
    Seasons: "2 seasons",
    Description: "A weak dungeon hunter is given a second chance through a mysterious power that lets him level up infinitely, turning him into humanity's strongest weapon.",
    Review: "Probably one of the most popular animes out there and it's either loved or hated. I personally think it's hated too much because it got so popular. The motivations from the MC are great from the start and evolve as he solves each problem. There's a bigger story than what initially meets the eye although I need to be clear: this is a power fantasy where the MC's purpose is aura farming. That doesn't mean it's not entertaining — it absolutely is. But if you're looking for some philosophical message, this isn't the place. The side characters are lacking in proper development, and as said before the 'meat' is just aura farming.",
    Tags: ["action","animation","intense","op-mc","epic-battles","aura-farming","power-system"],
    Studio: "A-1 Pictures",
    Platforms: ["Crunchyroll","Amazon Video","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/I6JIwjWOhnQ",
  },
  {
    Title: "Black Clover",
    Genre: "Shonen / Action",
    Rating: "8/10",
    image: "black-clover.png",
    Seasons: "4 seasons, 1 movie",
    Description: "A magicless boy in a world of mages fights to become the Wizard King using raw grit and anti-magic powers.",
    Review: "Long storyline with connecting dots, solid fight scenes, can drag on at times, rooting for protagonist. For being 171 episodes I think the pacing is done pretty well. There are some slow arcs here and there but overall it's a good storyline. Animation is both great and okay but its definitely worth a watch.",
    Tags: ["action","underdog","world-building","arcs","magic","friendship","rivalry","epic-battles"],
    Studio: "Pierrot",
    Platforms: ["Crunchyroll","Netflix","Hulu","Amazon Video","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/Ln_imebEmAQ"
  },
  {
    Title: "Seven Deadly Sins",
    Genre: "Fantasy / Shonen",
    Rating: "5/10",
    image: "seven-deadly-sins.png",
    Seasons: "5 seasons, 3 movies",
    Description: "A fallen group of legendary knights reunites to save their kingdom from dark forces.",
    Review: "There's a reason this anime is known as the 'seven deadly frames' and it lives up to the name. For what its worth the storyline is interesting. On the otherhand character development is terrible, show definitely drags on. Season 1 was bearable but holy crap this show has so much grooming in it. Watch this if you're bored but yeah thats about it. Show had great potiential but it was wasted.",
    Tags: ["action","magic","world-building","grooming","romance","fan-service","epic-battles"],
    Studio: "A-1 Pictures & Studio DEEN",
    Platforms: ["Netflix","Amazon Video","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/wxcvbL6o55M"
  },
  {
    Title: "DanDaDan",
    Genre: "Action / Supernatural",
    Rating: "9/10",
    image: "dandadan.png",
    Seasons: "2 seasons",
    Description: "Two teenagers bet on the existence of aliens and ghosts. Turns out they were both right! Now they gotta deal with the consquences of finding out.",
    Review: "The first episode definitely forces most people to drop the anime since one of the MCs almost gets raped. Rest assured, nothing bad happens to any of the characters aside from what the plot needs (spoilers). The storyline is great and progresses well. Characters are well written and hilarious. The second season amps it up a little to where it gets confusing but overall, it's fine. Animations great, soundtrack stands out with its musical scores, and who doesn't love balls being the premise of the story haha.",
    Tags: ["action","aliens","supernatural","comedy","ghost","ost"],
    Studio: "Science SARU",
    Platforms: ["Netflix","Crunchyroll","Hulu"],
    Trailer: "https://www.youtube.com/embed/0XJxfbN36Uw"
  },
  {
    Title: "Parasyte: The Maxim",
    Genre: "Action / Supernatural",
    Rating: "9/10",
    image: "parasyte.png",
    Seasons: "1 season",
    Description: "A high-school student's right hand becomes host to a parasitic life form, forcing them to work together to fend off deadly parasite invasions threatening humanity.",
    Review: "The first few seconds immediately bring you to the reality that this anime is gonna be brutal. I really enjoyed that while this anime did have a ton of action scenes; the story could still get into thought provoking questions about the nature of humans and animals alike. There are also several emotionally heartbreaking scenes that I didn't expect; but that made it all the better. The pacing is good for the most part but slows down before the end. That ending, however, is perfect and fully ties up the story.",
    Tags: ["action","aliens","thought-provoking","survival","identity","dark-fiction"],
    Studio: "Madhouse",
    Platforms: ["Crunchyroll","HiDive","Hulu","Funimation","Amazon Video","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/XIkxx3JRt-U"
  },
  {
    Title: "Death Note",
    Genre: "Thriller / Supernatural",
    Rating: "8/10",
    image: "death-note.png",
    Seasons: "1 season, specials",
    Description: "A teenager is given the power to kill by writing a persons name in a special notebook.",
    Review: "MC is super smart but incredibly prideful. This anime has guys predicting moves 15 steps ahead of each other and honestly it's a lot. It definitely has a drop in quality after a certain point but the storyline in of itself was solid. Each character has good motivations. Definitely worth a watch. The ending is 50/50 depending on who you are as a person.",
    Tags: ["mystery","justice-vs-morality","thought-provoking","survival","good-vs-evil","dark-fiction","intense","supernatural"],
    Studio: "Madhouse",
    Platforms: ["Netflix","Hulu","Funimation","Amazon Video","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/BHUPZpSKkhk"
  },
  {
    Title: "Classroom of the Elite",
    Genre: "Mystery / Psychological",
    Rating: "9/10",
    image: "classroom-of-the-elite.png",
    Seasons: "3 seasons",
    Description: "Students within an elite high school have to deal with an unusual curriculum where deception, betrayal, and violence are all behind the scenes.",
    Review: "Great premise and storyline. Characters are fleshed out over time especially the MC whose abilities and backstory are perfectly revealed as the anime goes on. Fan service heavy in season 1 but the rest really picks up the plot. Overpowered MC.",
    Tags: ["psychological","drama","school","strategy","social-hierarchy","manipulation","trust","op-mc"],
    Studio: "Lerche",
    Platforms: ["Crunchyroll","Hulu","Amazon Video","HIDIVE","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/jOg75_8hAhM"
  },
  {
    Title: "Failure Frame: I Became the Strongest and Annihilated Everything With Low Level Spells",
    Genre: "Isekai / Fantasy",
    Rating: "6.5/10",
    image: "failure-frame.png",
    Seasons: "1 season",
    Description: "A class of students is summoned to another world, but one boy is cast aside after being labeled with a weak magic ability—only to discover that his power grows in unexpected and dangerous ways.",
    Review: "The premise is that the MC is focused on revenge after getting thrown out of the hero's party and while most revenge stories are satisfying, this one fails to deliver in a couple ways. It seems that the MC constantly changes his attitude around the anime leading you to believe he's completely forgotten about getting revenge. The animation randomly switches to 3D which completely kills the Immersion and never looks good. Aside from that, the story just isn't that good. However, if you are fan of watching overpowered MCs obliterate everyone then this is the show for you.",
    Tags: ["revenge","power-system","3D", "isekai","op-mc","betrayal","anti-hero"],
    Studio: "Seven Arcs",
    Platforms: ["Crunchyroll","Amazon Video","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/1MylZpB5dIo"
  },
  {
    Title: "Farming Life in Another World",
    Genre: "Isekai / Fantasy",
    Rating: "7.5/10",
    image: "farming-life-in-another-world.png",
    Seasons: "1 season",
    Description: "A man is given a second chance at life after being unfairly treated in his first one.",
    Review: "This anime is the perfect way to relax after a long day. No stakes but pretty satisfying to watch the MCs farm and community grow. While it's not groundbreaking in any way, the music did stand out as a highlight. Nothing particularly bad or amazing it's just a chill experience.",
    Tags: ["slice-of-life","farming","relaxing","wholesome","community"],
    Studio: "ZERO-G",
    Platforms: ["HIDIVE","Amazon Video","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/hXIavkzdt4Y"
  },
  {
    Title: "Alya Sometimes Hides Her Feelings In Russian",
    Genre: "Romance / Slice of Life",
    Rating: "9/10",
    image: "alya-sometimes-hides.png",
    Seasons: "1 season",
    Description: "A sharp-tongued high school girl secretly expresses her feelings toward her classmate in Russian, believing he can't understand her—unaware that he hears every word.",
    Review: "This anime produced an amazing storyline for such a basic high school setting. The MC has a backstory which isn't fully disclosed and is slowly explored as the season progresses. The interactions are unique between the two MCs since I haven't seen this trope ever done in an anime before leading to great and cute moments. There is a bit of fan service but that doesn't take away from how good this love story is. Highly recommend it.",
    Tags: ["fan-service","school","romcom","wholesome","drama","student-council"],
    Studio: "Doga Kobo",
    Platforms: ["Crunchyroll","Amazon Video","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/CgacdWLGd0Y"
  },
  {
    Title: "My Dress Up Darling",
    Genre: "Romance / Slice of Life",
    Rating: "9/10",
    image: "my-dress-up-darling.png",
    Seasons: "2 seasons",
    Description: "A shy boy devoted to doll-making unexpectedly bonds with a popular girl through their shared interest in cosplay, leading to personal growth and a slowly developing romance.",
    Review: "Cute and highly enjoyable romance anime with a unique premise. The characters are really well written and enjoyable to watch as they develop. Be warned this is definitely a fan service heavy anime. Pacing is done well and overall; it has a solid buildup. Incredibly sweet and bingeable in a single night.",
    Tags: ["fan-service","cosplay","romcom","wholesome","school"],
    Studio: "CloverWorks",
    Platforms: ["Crunchyroll","Amazon Video","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/8oveGY6h6T8"
  },
  {
    Title: "The Girl I Like Forget Her Glasses",
    Genre: "Romance / Slice of Life",
    Rating: "9/10",
    image: "the-girl-i-like-forgot-her-glasses.png",
    Seasons: "1 season",
    Description: "A high school girl always forgets her glasses leading to cute and awkward moments with the boy that likes her.",
    Review: "This anime showcases incredibly unique and beautiful cinematography I haven't seen in an anime before. There exists a slow natural buildup between the MCs that's incredibly cute and wholesome to watch. While the gimmick may seem dumb there's a good reason behind it and overall, it's just a nice watch. The ending of season 1 leaves in a spot where season 2 can really shine.",
    Tags: ["romance","animation","romcom","wholesome","school", "cute"],
    Studio: "GoHands",
    Platforms: ["Crunchyroll","Apple TV+","Amazon Video","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/na8dVrRMj_8"
  },
  {
    Title: "The Dangers in My Heart",
    Genre: "Romance / Slice of Life",
    Rating: "9.5/10",
    image: "the-dangers-in-my-heart.png",
    Seasons: "2 seasons, 1 OVA",
    Description: "A lonely boy obsessed with dark thoughts starts falling for the cheerful girl who keeps noticing him.",
    Review: "Wholesome and emotionally grounded romance with a slow burn feel. The MC starts out pretty weird but quickly gets better. Pacing is good and rewarding. Couple dumb scenes but that comes out of most romance anime. One of the longer form romance animes currently out there.",
    Tags: ["romance","animation","romcom","personal-growth","school"],
    Studio: "Shin-Ei Animation",
    Platforms: ["HIDIVE","Apple TV+","Amazon Video","Shudder","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/x-cTWEpQu_A"
  },
  {
    Title: "Kubo Won't Let Me Be Invisible",
    Genre: "Romance / Slice of Life",
    Rating: "9/10",
    image: "kubo-wont-let-me-be-invisible.png",
    Seasons: "1 season",
    Description: "A quiet high school boy who fades into the background is repeatedly brought out of obscurity by a spirited classmate who refuses to let him stay invisible.",
    Review: "A very lovely and charming anime where the characters are entertaining; even all the side ones. I recommend binging this anime in a single night since it just makes you smile with all the in-class interactions between the MCs. There's nothing super great about it and nothing bad about this anime. As usual, the first season ended with a lot of potential for the second season, but nothing has been announced yet since the anime never got too popular.",
    Tags: ["romance","school","romcom","teasing","cute","wholesome"],
    Studio: "Pine Jam",
    Platforms: ["HiDive","Amazon Video","Apple TV+","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/muy4GpTL2Bg"
  },
  {
    Title: "Our Dating Story: The Experienced You and The Inexperienced Me",
    Genre: "Romance / Drama",
    Rating: "7/10",
    image: "our-dating-story.png",
    Seasons: "1 season",
    Description: "A socially awkward high school boy unexpectedly begins dating one of the most popular girls in his class, forcing both of them to confront their insecurities, expectations, and very different experiences with love.",
    Review: "Not the most generic romance anime but it does get incredibly stupid at times. The first 7 episodes are interesting, but it gets a little dull after that. The ending comes back and ties everything up with a wholesome ending. If anything, the side character plots are just as intriguing if not more engaging than the main plot. Again, the ending is quite wholesome so if you're looking for average binge worthy content, look no further. ",
    Tags: ["romance","school","romcom","drama","fan-service"],
    Studio: "ENGI",
    Platforms: ["Crunchyroll","Apple TV+","Amazon Video","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/HYfDGdnfbuY"
  },
  {
    Title: "More Than a Married Couple but Not Lovers",
    Genre: "Romance / Drama",
    Rating: "9/10",
    image: "more-than-a-married-couple.png",
    Seasons: "1 season",
    Description: "Two high school classmates are paired together in a mandatory “marriage practical” program where they must act like a married couple to earn the right to change partners, despite their vastly different personalities and initial reluctance; they slowly start falling for each other.",
    Review: "What starts out as a seemingly gooner anime quickly turns to sweet tension between 2 characters who initially hated each other. The tender moments between the MCs really make this anime for me. On a dime it can turn from a seemingly angry argument to real emotions. As the story progresses the tender moments only increase, and the characters slowly begin to change. I love the dynamic changes that occur throughout the story. By the end I fell in love with this anime and as time passed I only grew to like it more. One of my all-time favorite romances.",
    Tags: ["romance","school","romcom","fan-service","live-together","sweet","wholesome"],
    Studio: "Studio MOTHER",
    Platforms: ["Crunchyroll","Apple TV+","Amazon Prime Video","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/s4p1FStY_v0",
    Top10Rank: 6
  },
  {
    Title: "Days with My Stepsister",
    Genre: "Romance / Drama",
    Rating: "10/10",
    image: "days-with-my-stepsister.png",
    Seasons: "1 season",
    Description: "A high school boy and girl, unrelated by blood, suddenly become step siblings. Now having to live together they carefully navigate their new relationship.",
    Review: "Do not let the title fool you. This is very different from all the other romance/slice of life animes out there. The pacing is realistic and patient. The MCs are intelligent and relatable. They show genuine emotion, restraint, and introspection to their situation. The anime avoids cliches and handles complex emotions with subtlety. There's a contemplative nature to every episode and I just haven't seen this before in an anime. The background music is always soothing, almost meditative allowing the scenes to be fleshed out and contemplated.",
    Tags: ["romance","school","drama","fan-service","live-together","thought-provoking","soundtrack","calming","personal-growth"],
    Studio: "Studio DEEN",
    Platforms: ["Crunchyroll","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/_laWs_MfqN8"
  },
  {
    Title: "My Stepmom's Daughter Is My Ex",
    Genre: "Romance / Drama",
    Rating: "8.5/10",
    image: "my-stepmoms-daughter-is-my-ex.png",
    Seasons: "1 season",
    Description: "Two exes are forced to live in the same house after their parents remarry.",
    Review: "I liked how this anime slowly explored the goods/bads that come from a previous relationship and the growth it provides. It's continently brought back up and is Important to the grand narrative.  Now being apart of a family also leads to interesting perspectives. The side characters don't vanish and are actually present. The pacing is too quick in the first couple episodes but fixes itself. The ending does leave some questions but that's because the light novel has more to go. Overall it's a thoughtful and enjoyable anime.",
    Tags: ["romance","school","drama","fan-service","live-together"],
    Studio: "Project No. 9",
    Platforms: ["Crunchyroll","Amazon Video","aniwave"],
    Trailer: "https://www.youtube.com/embed/OJ_kXEOVjvg"
  },
  {
    Title: "Boarding School Juliet",
    Genre: "Romance / Drama",
    Rating: "9/10",
    image: "boarding-school-juliet.png",
    Seasons: "1 season",
    Description: "Within a prestigious boarding school there exist two rival factions: The white cats and black doggies. What happens when the leader of the black cats falls in love with the other rival leader?",
    Review: "Honestly underrated comedy. This one had some funny moments that really made the anime. For the most part characters are solid and only a couple cringy moments exist. Definitely a feel-good watch.",
    Tags: ["romance","rival-schools","romcom","secret-relationship","enemies-to-lovers"],
    Studio: "LIDENFILMS",
    Platforms: ["Funimation","Amazon Video","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/TV_jnYsumck"
  },
  {
    Title: "An Archdemon's Dilemma: How to Love Your Elf Bride",
    Genre: "Fantasy / Romance",
    Rating: "9/10",
    image: "archdemons-dilemma.png",
    Seasons: "1 season",
    Description: "A feared and immensely powerful sorcerer unexpectedly falls in love after purchasing an enslaved elf girl, only to discover that expressing his feelings may be harder than mastering magic itself.",
    Review: "A surprising, cute and delightful anime that surprised in terms of quality in almost every way. The storyline: Top tier. Characters: Amazing. Magic System: Intricate and thoroughly explained. So many good moments from this anime where the characters shine. Several funny moments I wasn't expecting made me laugh. Absolutely binge worthy.",
    Tags: ["romance","fantasy","romcom","magic","live-together","heartwarming","elves","comedy"],
    Studio: "Brains Base",
    Platforms: ["Crunchyroll","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/52mVoy7ZYRY"
  },
  {
    Title: "Rascal Does Not Dream of Bunny Girl Senpai",
    Genre: "Supernatural / Romance",
    Rating: "10/10",
    image: "bunny-girl-senpai.png",
    Seasons: "2 seasons, 3 movies",
    Description: "Puberty syndrome - Abnormal experiences rumored on the internet to be caused by sensitivity and instability during adolescence. This year, Sakuta Azusagawa, a second-year student at a high school near Enoshima, meets several girls that are experiencing this “puberty syndrome.” For instance, he meets a wild bunny girl in the library. She turns out to be an actress on hiatus, Mai Sakurajima, who is also his senior at the school. For some reason, no one else can see this enchanting girl. How did she become invisible…?",
    Review: "Do not let the title fool you. This is probably one of the most intricate, well written, and emotionally heart pulling romance amines that exist. The supernatural element really brings in the show and characters since it’s that unknown element that fully brings the 2 MCs together. The relationship that’s developed is probably the sweetest thing I’ve seen in a long time. The soundtrack, side characters, and animation all excel along with the story. The anime doesn't only focus on the main characters, which is so nice because honestly one of the things that stuck with me most happened with side characters. This is a definite watch if you're looking to feel joy, heartbreak, and all the things in-between.",
    Tags: ["romance","psychological","romcom","drama","identity","complex","heartwarming","emotional-trauma","healing"],
    Studio: "CloverWorks",
    Platforms: ["Crunchyroll","Hulu","Amazon Video","Netflix w VPN","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/4H_t9Dlk0mo"
  },
  {
    Title: "The Magical Girl and the Evil Lieutenant Used to Be Archenemies",
    Genre: "Supernatural / Romance",
    Rating: "8/10",
    image: "the-magical-girl.png",
    Seasons: "1 season",
    Description: "The most evil man on the planet instantly falls in love with an enemy.",
    Review: "Sweet romcom. Episodes are really short so this is 100% an anime to binge in a single night. Wholesome with good characters and funny moments. Sadly, the author passed away and this anime will not be continued passed season 1. you can read the light novel that slightly expands past the end of season 1 but thats it.",
    Tags: ["romance","enemies-to-lovers","romcom","comedy","magic","wholesome"],
    Studio: "A-1 Pictures",
    Platforms: ["Crunchyroll","Apple TV+","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/YwzmC_qBS7k"
  },
  {
    Title: "Princess Mononoke",
    Genre: "Fantasy / Romance",
    Rating: "8.9/10",
    image: "princess-mononoke.png",
    Seasons: "1 movie",
    Description: "A young warrior sets off west to find a cure for his curse that gives him unmatched strength.",
    Review: "Overall an incredibly well-crafted story where the movie never went in a predictable direction and kept me on my toes. The movie explored several ideas and themes including war and peace while asking difficult questions. The most interesting premise of the film was exploring the idea of being able to take both sides of a war. The only complaint  was that I felt the ending was a bit abrupt. Again, a beautiful story and I highly recommend it.",
    Tags: ["thought-provoking","enemies-to-lovers","romance","folklore","war-and-peace","animal-human-conflict"],
    Studio: "Studio Ghibli",
    Platforms: ["HBO Max","Amazon Prime Video", "Apple TV+", "Fandango"],
    Trailer: "https://www.youtube.com/embed/4OiMOHRDs14"
  },
  {
    Title: "Hatsune Miku: Colorful Stage! A Miku Who Can't Sing",
    Genre: "Musical / Idol",
    Rating: "5/10",
    image: "miku-movie.png",
    Seasons: "1 movie",
    Description: "A musical style movie set in a world where music is very popular.",
    Review: "Let me be clear: Musicals are not my area of expertise so... The movie itself I feel like had WAY too many main characters to keep track of. Certain plot points weren't explained well. I can't judge the music itself but I'm just not into this kinda thing hence the rating. Objectively it might be better but.",
    Tags: ["music","idol","confusing","miku","domain-expansions-idk"],
    Studio: "Studio Colorido",
    Platforms: ["Blu-ray"],
    Trailer: "https://www.youtube.com/embed/3bD1dfiRMu4"
  },
  {
    Title: "Frieren: Beyond Journey's End",
    Genre: "Fantasy / Drama",
    Rating: "10/10",
    image: "frieren.png",
    Seasons: "2 seasons",
    Description: "A poetic fantasy that follows Frieren, an immortal elf mage revisiting the world decades after her heroic party defeated the Demon King, exploring profound themes of time, memory, and the value of fleeting human connections.",
    Review: "This story can easily be dismissed as boring or too slow for most audiences who are so used to immediate dopamine in large-scale action, and there's nothing wrong with that. Frieren takes a step back and genuinely answers the question of what it's like to have a long lifespan. The flashbacks are important, the animation is absolutely stellar, and the characters are perfect. The introspection Frieren has when she starts to consider that her limited time with others is valuable. The story is interesting and doesn't just follow the MC. Even with an overpowered protagonist, the fights are interesting and well done. The magic system is explained well, and overall it's a very enjoyable watch.",
    Tags: ["introspective","magic-worldbuilding","animation","reflective","contemplative","story"],
    Studio: "Studio Madhouse",
    Platforms: ["Crunchyroll","Netflix","Hulu","Amazon Video","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/Iwr1aLEDpe4"
  },
  {
    Title: "Chainsaw Man",
    Genre: "Shonen / Action",
    Rating: "9/10",
    image: "chainsaw-man.png",
    Seasons: "1 season, 1 Movie",
    Description: "A destitute young man merges with his pet devil to survive in a brutal world, becoming a government devil hunter while navigating violence, manipulation, and his own twisted desires.",
    Review: "While taken at surface value this anime seems it was made for the gooners of society, in reality I promise it’s not. The MC is honestly relatable when it comes to just getting through life and finding meaning. His problem though is that he doesn't understand where to find that meaning. Is it through love? Food? Friends? All of these questions are addressed, and the darkness of reality slowly shines through. There are some pretty funny moments that made me laugh in season 1, but the reze arc movie really kicks up anti. It went from hey this is kinda chill to “lets teach the audience the meaning of life” and holy did it work. The side characters are great and have a place in the story, the animation is peak since MAPPA produced it, and as expected its fan service heavy.",
    Tags: ["fan-service","anti-hero","animation","gritty","supernatural","twists"],
    Studio: "MAPPA",
    Platforms: ["Crunchyroll","Hulu","Amazon Video","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/l96zmDlWCBk"
  },
  {
    Title: "Apocalypse Bringer Mynoghra",
    Genre: "Isekai / Fantasy",
    Rating: "7/10",
    image: "apocalypse-bringer.png",
    Seasons: "1 season",
    Description: "After dying young, Takuto is reborn in a game-like world with his demonic servant and seeks to build a civilization from ruin.",
    Review: "This anime has a solid premise that I think just could have been executed better. The animation is clearly lacking but not to the point where it ruins the anime. I will say that this can quickly turn from a fun filled comedy to serious merciless moments in a flash; it definitely surprised me in that aspect. The ending was pretty good and I'm excited for season 2.",
    Tags: ["nation-building","strategy","power-growth","mid-animation","supernatural","romance"],
    Studio: "Maho Film",
    Platforms: ["Crunchyroll","Amazon Prime","Apple TV+","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/OTL_4Fxwwtw"
  },
  {
    Title: "The Foolish Angel Dances with the Devil",
    Genre: "Supernatural / Romance",
    Rating: "8/10",
    image: "foolish-angel.png",
    Seasons: "1 season",
    Description: "A demon infiltrating the human world falls for a stern angel — who secretly plots to reform him — leading to a chaotic celestial romance.",
    Review: "Personally, I feel like the MC started off really annoying and stupid. The plot was predictable and I really didn't think the anime was gonna go anywhere. Last 4-5 episodes did really well though and the animation surprised me. They balance the drama of school with the wars between heaven and hell pretty well in my opinion. Solid watch.",
    Tags: ["enemies-to-lovers","angels","demons","school-life","wholesome","comedy"],
    Studio: "Children's Playground Entertainment",
    Platforms: ["Crunchyroll","Amazon Video","Apple TV+","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/KC1Hz-4L1yY"
  },
  {
    Title: "The Ice Guy and His Cool Female Colleague",
    Genre: "Romance / Slice of Life",
    Rating: "8.5/10",
    image: "the-ice-guy.png",
    Seasons: "1 season",
    Description: "A quiet office romance between a man descended from yuki-onna spirits and his calm, kind coworker, told through gentle everyday interactions.",
    Review: "An absolutely heartwarming and wholesome anime. Perfect to put on if you're looking for sweet interactions, well written characters, and a slow burn love over 12 episodes. Nothing overly stressful ever occurs and what else can I say. Definitely go give it a watch.",
    Tags: ["office-romance","wholesome","slowburn","supernatural","comfort-anime","romance"],
    Studio: "Liber & ZERO-G",
    Platforms: ["Crunchyroll","Amazon Prime Video","Apple TV+","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/mgmHhWqoU54"
  },
  {
    Title: "Gachiakuta",
    Genre: "Fantasy / Action",
    Rating: "9.5/10",
    image: "gachiakuta.png",
    Seasons: "1 season",
    Description: "In a brutal, discarded underworld beneath a floating city, a boy falsely accused of murder is forced to survive among monsters and corruption while uncovering the truth behind the world that threw him away.",
    Review: "Top tier new gen anime right here. The content gets down into the nitty gritty dark holes of society where our MC character explores the ideas of 'useless' and whats considered 'trash' in society in such a tangable way. The animation is amazing with plenty of impact frames and hardcore drawings to go with the action. The world building is fantastic with the plot following along perfectly. The only problem I had with this anime was that pacing during the fight scenes could have been done better. But don't let that stop you from watching this fanatastic anime.",
    Tags: ["dark-fantasy","action","animation","gritty","revenge","survival", "supernatural", "philosphical"],
    Studio: "Bones",
    Platforms: ["Crunchyroll","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/-DWElt4GtAc"
  },
  {
    Title: "The Water Magician",
    Genre: "Isekai / Fantasy",
    Rating: "8/10",
    image: "water-magician.png",
    Seasons: "1 season",
    Description: "Reborn into a magical new world with water magic and eternal youth, a man hopes for a peaceful life but is pulled into adventure and danger as he grows into his power and impacts the world around him.",
    Review: "This anime showcases gorgeous water painted backgrounds that are super unique. All the characters are great and have a place in the world with even background characters showing up consistently and developing personalities. Honestly, the only thing lacking with this anime is the animation. The storytelling, design, and context are all exceptional for a fantasy. Just wish the fight scenes had some more juice behind them.",
    Tags: ["action","dragons","survival", "elves","magic","demons","backgrounds"],
    Studio: "Typhoon Graphics & Wonderland",
    Platforms: ["Crunchyroll","Amazon Video","Apple TV","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/vQWodcG5x-I"
  },
  {
    Title: "Watari-kun's ****** Is About to Collapse",
    Genre: "Romance / Drama",
    Rating: "9/10",
    image: "Watari-kun.png",
    Seasons: "1 season",
    Description: "A responsible young man raising his little sister finds his carefully balanced life disrupted when a tragic childhood friend returns, forcing him to navigate complicated relationships, unresolved past feelings, and the emotional fallout that comes with them.",
    Review: "I have a lot to say. The first thing being: give this anime a chance. I made a mistake by going into this anime under the assumption that it was going to be a supernatural-heavy romance story. It's not. There are no supernatural elements, and for the first half the plot isn't overly serious. In fact, it's actually quite terrible. There is a gross overuse of ecchi fan service that I can't stand, as well as an infuriatingly dense, horny, and clueless main character who flip-flops on his emotions in a second. Couple that with a show that's trying to be too many genres at once, and I was going to drop it. However, I kept watching. The second cour feels like a completely different show. The 26-episode length finally let it breathe, quickly shifting from retarded ecchi clichés to a real story. The main character underwent captivating development that completely changed the direction of the anime. It transcended a bait-and-switch trope to ask real questions about abandonment, obsession, forgiveness, and rebuilding after trauma. The love triangle was dealt with nicely, and the anime went past the classic high school-only romance to show what thinking about a real future is like. In the end, the first 13 episodes weren't useless but allowed a greater story to be told. All that was left was a heartfelt emotional triumph that'll stick with me long after I write this review. A messy start, but a journey worth every step. There will be no more seasons; this was a complete adaptation of the original manga.",
    Tags: ["seinen","love-triangle","school", "relationships","emotional","character-growth","coming-of-age","complex","fan-service","ecchi","thought-provoking"],
    Studio: "Staple Entertainment",
    Platforms: ["Crunchyroll","Amazon Video","Apple TV","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/iPBqQWx-OX0",
    Top10Rank: 9
  },
  {
    Title: "My Status as an Assassin Obviously Exceeds the Hero's",
    Genre: "Isekai / Fantasy",
    Rating: "7/10",
    image: "StatusAssassin.png",
    Seasons: "1 season",
    Description: "A quiet and overlooked student is transported to another world as an assassin, where his true abilities far surpass those of the chosen hero.",
    Review: "This anime features incredibly sharp and detailed character models that looked sick. While the animation looks strong in the opening shot of the first episode, the overall quality from the rest of the anime isn't up to par. The MC is definitely interesting in terms of his philosophy with others, but he does have some cringy moments as well. Didn't find the side characters particularly entertaining or unique, and the first season never felt like it went anywhere story wise. Now that may open up in the second season, but for now I can only describe this anime as lackluster.",
    Tags: ["assassin","op-mc","revenge","magic","dark-fantasy","anti-hero","power-system","combat","survival","stealth"],
    Studio: "Studio Sunrise",
    Platforms: ["Crunchyroll","Prime Video","Apple TV","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/gZQjg_YLxPw"
  },
];


