// AUTO-GENERATED by scripts/sync-excel-to-js.js — do not edit by hand.
// Source of truth: ../Master List/Anime_Master_Table.xlsx
// Last sync: 2026-06-03T17:22:32.118Z

const animeData = [
  {
    Title: "One punch man",
    Genre: "Shonen/Action",
    Rating: "7/10",
    image: "one-punch-man.png",
    Seasons: "2 seasons, specials",
    Description: "A superhero who can defeat any opponent with a single punch struggles to find purpose and excitement in a world where no battle challenges him.",
    Review: "Definition of falling from glory. The anime is at its core an ironic comedy since the MC cannot lose a fight, so it focuses on the other struggles he has. A very unique premise where they balance out that storyline with intricate side characters who are thoroughly written and explored. Animation was also insane for the first 2 seasons. There are times when the fan service is heavy but bear with it. The anime knows to create a meaningful and powerful story even when the entire premise is ultimately around a character that’s too strong for any battle. Unfortunately, perfection comes at a cost. Season 3 did not deliver anything close to the quality and authenticity of the first two seasons. It’s sad but we can hope it one day gets revived. Mind you, the first two seasons are amazing but that third season is what brings the rating so low.",
    Tags: ["action","animation","comedy","fan-service","op-mc"],
    Studio: "Madhouse, J.C Staff",
    Platforms: ["Amazon Video","Hulu","Netflix","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/Poo5lqoWSGw"
    ,AniListId: 21087
    ,IdMal: 30276
    ,AniListScore: 83
    ,AniListColor: "#e4ae5d"
    ,TitleEnglish: "One-Punch Man"
    ,TitleRomaji: "One Punch Man"
    ,TitleNative: "ワンパンマン"
  },
  {
    Title: "Demon slayer",
    Genre: "Shonen/Action",
    Rating: "9/10",
    image: "demon-slayer.png",
    Seasons: "5 seasons",
    Description: "A boy joins the Demon Slayer Corps after his family is slaughtered and his sister is turned into a demon vowing to restore her to a human.",
    Review: "Unbelievable animation, you feel for the characters, rise to power. The story arcs are incredibly well done. All characters are given due justice and the world buildup is great. People shit on this anime for just being \"eye candy\" but \r\r\nI don't get it. There is clear character progression, well told backstories that influence the story, power systems, and characters actually get killed off. Yeah the animation is great and i'm not denying that. I think this is a classic case of \r\r\nan anime that got too popular so its gets hated on. Solid watch from me.",
    Tags: ["action","animation","epic-battles","revenge"],
    Studio: "Ufotable",
    Platforms: ["Netflix","Crunchyroll","Amazon Video","Hulu","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/VQGCKyvzIM4"
    ,AniListId: 101922
    ,IdMal: 38000
    ,AniListScore: 83
    ,AniListColor: "#f1c9ae"
    ,TitleEnglish: "Demon Slayer: Kimetsu no Yaiba"
    ,TitleRomaji: "Kimetsu no Yaiba"
    ,TitleNative: "鬼滅の刃"
  },
  {
    Title: "Chainsaw Man",
    Genre: "Shonen/Action",
    Rating: "9/10",
    image: "chainsaw-man.png",
    Seasons: "1 season",
    Description: "A destitute young man merges with his pet devil to survive in a brutal world, becoming a government devil hunter while navigating violence, manipulation, and his own twisted desires.",
    Review: "While taken at surface value this anime seems it was made for the gooners of society, in reality I promise it’s not. The MC is honestly relatable when it comes to just getting through life and finding meaning. His problem though is that he doesn’t understand where to find that meaning. Is it through love? Food? Friends? All of these questions are addressed, and the darkness of reality slowly shines through. There are some pretty funny moments that made me laugh in season 1, but the reze arc movie really kicks up anti. It went from hey this is kinda chill to “lets teach the audience the meaning of life” and holy did it work. The side characters are great and have a place in the story, the animation is peak since MAPPA produced it, and as expected its fan service heavy.",
    Tags: ["fan-service","anti-hero","gritty","supernatural"],
    Studio: "MAPPA",
    Platforms: ["Crunchyroll","Amazon Video","Hulu","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/l96zmDlWCBk"
    ,AniListId: 127230
    ,IdMal: 44511
    ,AniListScore: 83
    ,AniListColor: "#6b1a1a"
    ,TitleEnglish: "Chainsaw Man"
    ,TitleRomaji: "Chainsaw Man"
    ,TitleNative: "チェンソーマン"
  },
  {
    Title: "Kaiju No. 8",
    Genre: "Shonen/Action",
    Rating: "9/10",
    image: "kaiju-no-8.png",
    Seasons: "2 seasons",
    Description: "In a world plagued by monstrous kaiju attacks, a middle-aged cleanup worker unexpectedly gains the ability to transform into a kaiju himself, forcing him to secretly pursue his dream of joining the elite defense force sworn to eradicate the very creatures he has become.",
    Review: "Few beat Kaiju. No 8 in consideration of goated animation and fight scenes. This anime features an awesome MC who you can’t help but root for the entire way. Not only that but the side characters all have compelling stories and motivations. Season 2 continues after the cliff hanger of season 1 and continues building up the plot in powerful and decisive moments. The only thing that holds back this anime is following a generic shonen plot with a few cliches that are overdone. For sure one of the bigger modern anime titles.",
    Tags: ["kaiju","military","animation","duty","fight-scenes","plot-thickens"],
    Studio: "Production I.G",
    Platforms: ["Crunchyroll","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/JwF7bhvnCxI"
    ,AniListId: 153288
    ,IdMal: 52588
    ,AniListScore: 81
    ,AniListColor: "#f1e4ae"
    ,TitleEnglish: "Kaiju No. 8"
    ,TitleRomaji: "Kaijuu 8-gou"
    ,TitleNative: "怪獣８号"
  },
  {
    Title: "Jujutsu Kaisen",
    Genre: "Shonen/Action",
    Rating: "10/10",
    image: "jjk.png",
    Seasons: "2 seasons, 1 movie",
    Description: "A high school student becomes host to a powerful curse and is drawn into the hidden world of jujutsu sorcerers, where he must fight deadly supernatural threats while struggling to retain his humanity.",
    Review: "One of the big 3 in modern anime and it absolutely delivers on that title. MAPPA studio delivers some of the most unbelievable animation paired with fight choreography that’s out of this world. It’s one of those rare cases where an anime can have such serious moments and important events while maintaining humorous and slice of life moments. There are so many characters that stand out and provide such an important role to the story that they simply take over the anime world. I guarantee that this show has had more of an impact on human culture than some actual real events happening today. It’s that good. If you haven’t watched this phenomenon show. Go watch it. Oh sorry did I not mention Gojo and toji?",
    Tags: ["action","intense","supernatural","curses","sorcery"],
    Studio: "MAPPA",
    Platforms: ["Crunchyroll","Netflix","Hulu","Amazon Prime Video","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/pkKu9hLT-t8"
    ,Top10Rank: 10
    ,AniListId: 113415
    ,IdMal: 40748
    ,AniListScore: 84
    ,AniListColor: "#e45d5d"
    ,TitleEnglish: "JUJUTSU KAISEN"
    ,TitleRomaji: "Jujutsu Kaisen"
    ,TitleNative: "呪術廻戦"
  },
  {
    Title: "Solo Leveling",
    Genre: "Shonen/Action",
    Rating: "9/10",
    image: "solo-leveling.png",
    Seasons: "2 seasons",
    Description: "A weak dungeon hunter is given a second chance through a mysterious power that lets him level up infinitely, turning him into humanity’s strongest weapon.",
    Review: "Probably one of the most popular animes out there and it's either loved or hated. I personally think it's hated too much because it got so popular. The motivations from the MC are great from the start and evolve as he solves each problem. \r\r\nThere's a bigger story than what initially meets the eye although I need to be clear: this is a power fantasy where the MC’s purpose is aura farming. That doesn't mean it's not entertaining — it absolutely is. But if you're looking for some \r\r\nphilosophical message, this isn't the place. The side characters are lacking in proper development, and as said before the \"meat\" is just aura farming.",
    Tags: ["op-mc","animation","action","fepic-battles","fights","power-system","aura-farming"],
    Studio: "A1 Pictures",
    Platforms: ["Crunchyroll","Amazon Video","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/I6JIwjWOhnQ"
    ,AniListId: 151807
    ,IdMal: 52299
    ,AniListScore: 81
    ,AniListColor: "#35bbf1"
    ,TitleEnglish: "Solo Leveling"
    ,TitleRomaji: "Ore dake Level Up na Ken"
    ,TitleNative: "俺だけレベルアップな件"
  },
  {
    Title: "Black Clover",
    Genre: "Fantasy/Shonen",
    Rating: "8/10",
    image: "black-clover.png",
    Seasons: "4 seasons, 1 movie",
    Description: "A magicless boy in a world of mages fights to become the Wizard King with raw grit and anti-magic powers.",
    Review: "Long storyline with connecting dots, solid fight scenes, can drag on at times, rooting for protagonist. For being 171 episodes I think the pacing is done pretty well. There are some slow arcs here and there but overall it’s a good storyline. Animation is both great and okay but its definitely worth a watch.",
    Tags: ["action,","underdog,","worldbuilding,","arcs,","magic,","friendly,-rivalry"],
    Studio: "Pierrot",
    Platforms: ["Crunchyroll","Netflix","Amazon Video","Hulu","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/Ln_imebEmAQ"
    ,AniListId: 97940
    ,IdMal: 34572
    ,AniListScore: 79
    ,AniListColor: "#d6c96b"
    ,TitleEnglish: "Black Clover"
    ,TitleRomaji: "Black Clover"
    ,TitleNative: "ブラッククローバー"
  },
  {
    Title: "Frieren: Beyond Journey’s End",
    Genre: "Fantasy/Drama",
    Rating: "10/10",
    image: "frieren.png",
    Seasons: "1 season",
    Description: "A poetic fantasy that follows Frieren, an immortal elf mage revisiting the world decades after her heroic party defeated the Demon King, exploring profound themes of time, memory, \r\r\nand the value of fleeting human connections.",
    Review: "This story can easily be dismissed as boring or too slow for most audiences who are so used to immediate dopamine in large‑scale action, and there's nothing wrong with that. Frieren takes a step back and genuinely answers the question of what it's like to have a long lifespan. The flashbacks are important, the animation is absolutely stellar, and the characters are perfect. The introspection Frieren has when she starts to consider that her limited time with others is valuable. The story is interesting and doesn't just follow the MC. Even with an overpowered protagonist, the fights are interesting and well done. The magic system is explained well, and overall it's a very enjoyable watch.",
    Tags: ["introspective,","magic","worldbuilding,","animation,","reflective,","contemplative,","story"],
    Studio: "Studio Madhouse",
    Platforms: ["Crunchyroll","Netflix","Hulu","Amazon Video","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/Iwr1aLEDpe4"
    ,AniListId: 154587
    ,IdMal: 52991
    ,AniListScore: 91
    ,AniListColor: "#bbf1a1"
    ,TitleEnglish: "Frieren: Beyond Journey’s End"
    ,TitleRomaji: "Sousou no Frieren"
    ,TitleNative: "葬送のフリーレン"
  },
  {
    Title: "Seven Deadly Sins",
    Genre: "Fantasy/Shonen",
    Rating: "5/10",
    image: "seven-deadly-sins.png",
    Seasons: "5 seasons, 3 movies",
    Description: "A fallen group of legendary knights reunites to save their kingdom from dark forces.",
    Review: "There's a reason this anime is known as the \"seven deadly frames\" and it lives up to the name. For what its worth the storyline is interesting. On the otherhand character development is uh okay, show definitely drags on. Season 1 \r\r\nwas bearable but holy crap this show has so much grooming in it. Watch this if you're bored but yeah thats about it. Show had great potiential but it was wasted.",
    Tags: ["magic,","worldbuilding,","grooming,","romance,","fanservice"],
    Studio: "A-1 Pictures, Studio Deen",
    Platforms: ["Netlfix","Amazon Video","hianime","9amime","aniwave"],
    Trailer: "https://www.youtube.com/embed/wxcvbL6o55M"
    ,AniListId: 20789
    ,IdMal: 23755
    ,AniListScore: 73
    ,AniListColor: "#e4861a"
    ,TitleEnglish: "The Seven Deadly Sins"
    ,TitleRomaji: "Nanatsu no Taizai"
    ,TitleNative: "七つの大罪"
  },
  {
    Title: "Gachiakuta",
    Genre: "Fantasy/Action",
    Rating: "9.5/10",
    image: "gachiakuta.png",
    Seasons: "1 season",
    Description: "In a brutal, discarded underworld beneath a floating city, a boy falsely accused of murder is forced to survive among monsters and corruption while uncovering the truth behind the world that threw him away.",
    Review: "Top tier new gen anime right here. The content gets down into the nitty gritty dark holes of society where our MC character explores the ideas of \"useless\" and whats considered \"trash\" in society in such a tangable way. The animation is amazing with plenty of impact frames and hardcore drawings to go with the action. The world building is fantastic with the plot following along perfectly. The only problem I had with this anime was that pacing during the fight scenes could have been done better. But don't let that stop you from watching this fanatastic anime.",
    Tags: ["dark-fantasy","action","animation","gritty","revenge","survival","combat","superatural","philosphical"],
    Studio: "Bones",
    Platforms: ["Crunchyroll"],
    Trailer: "https://www.youtube.com/embed/-DWElt4GtAc"
    ,AniListId: 178025
    ,IdMal: 59062
    ,AniListScore: 82
    ,AniListColor: "#e4a150"
    ,TitleEnglish: "Gachiakuta"
    ,TitleRomaji: "Gachiakuta"
    ,TitleNative: "ガチアクタ"
  },
  {
    Title: "Hell’s Paradise",
    Genre: "Action/Supernatural",
    Rating: "10/10",
    image: "hells-paradise.png",
    Seasons: "1 season",
    Description: "Elite Shinobi is in death row, but given a choice to go to a mysterious island to find an elixir of life in exchange for an official pardon.",
    Review: "Superb animation, good storyline, some sus scenes, fire score. This was one of those anime where you kinda take a step back and appreciate what greatness looks like. The motivations of the MC are incredibly thought out and yet there’s more than what meets the eye (spoilers). Fight choreography was incredible and the world building was also superb. One of my favorites.",
    Tags: ["action,","ninja,","redemption,","immortality,","humannauture,","ost,","combat"],
    Studio: "MAPPA",
    Platforms: ["Cruncyroll","Netflix","Hulu","Amazon Video","hianime","9anime"],
    Trailer: "https://www.youtube.com/embed/aaHZdwPZX6g"
    ,Top10Rank: 7
    ,AniListId: 128893
    ,IdMal: 46569
    ,AniListScore: 80
    ,AniListColor: "#e4bb35"
    ,TitleEnglish: "Hell’s Paradise"
    ,TitleRomaji: "Jigokuraku"
    ,TitleNative: "地獄楽"
  },
  {
    Title: "DanDaDan",
    Genre: "Action/Supernatural",
    Rating: "9/10",
    image: "dandadan.png",
    Seasons: "2 seasons",
    Description: "Two teenagers bet on the existence of aliens and ghosts. Turns out they were right! Now they gotta deal with the consquences of finding out.",
    Review: "The first episode definitely forces most people to drop the anime since one of the MCs almost gets raped. Rest assured, nothing bad happens to any of the characters aside from what the plot needs (spoilers). The storyline is great and progresses well. Characters are well written and hilarious. The second season amps it up a little to where it gets confusing but overall, it’s fine. Animations great, soundtrack stands out with its musical scores, and who doesn’t love balls being the premise of the story haha.",
    Tags: ["supernatural,","comedy,","action,","ghosts,","aliens,","ost"],
    Studio: "Science SARU",
    Platforms: ["Crunchyroll","Netflix","Hulu"],
    Trailer: "https://www.youtube.com/embed/0XJxfbN36Uw"
    ,AniListId: 171018
    ,IdMal: 57334
    ,AniListScore: 83
    ,AniListColor: "#e47850"
    ,TitleEnglish: "DAN DA DAN"
    ,TitleRomaji: "Dandadan"
    ,TitleNative: "ダンダダン"
  },
  {
    Title: "Parasyte: The Maxim",
    Genre: "Action/Supernatural",
    Rating: "9/10",
    image: "parasyte.png",
    Seasons: "1 season",
    Description: "A high-school student’s right hand becomes host to a parasitic life form, forcing them to work together to fend off deadly parasite invasions threatening humanity.",
    Review: "The first few seconds immediately bring you to the reality that this anime is gonna be brutal. I really enjoyed that while this anime did have a ton of action scenes; the story could still get into thought provoking questions about the nature of humans and animals alike. There are also several emotionally heartbreaking scenes that I didn’t expect; but that made it all the better. The pacing is good for the most part but slows down before the end. That ending, however, is perfect and fully ties up the story.",
    Tags: ["aliens,","thoughtprovoking,","identity","survival,","dark","action"],
    Studio: "Madhouse",
    Platforms: ["Crunchyroll","Hulu","Amazon Video","Funimation","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/rj63TDpaBWk"
    ,AniListId: 20623
    ,IdMal: 22535
    ,AniListScore: 81
    ,AniListColor: "#285086"
    ,TitleEnglish: "Parasyte -the maxim-"
    ,TitleRomaji: "Kiseijuu: Sei no Kakuritsu"
    ,TitleNative: "寄生獣 セイの格率"
  },
  {
    Title: "Death Note",
    Genre: "Thriller/Supernatural",
    Rating: "8/10",
    image: "death-note.png",
    Seasons: "1 season, specials",
    Description: "A teenager is given the power to kill by writing a persons name in a special notebook.",
    Review: "MC is super smart but prideful. This anime has guys predicting moves 15 steps ahead of each other and it’s a lot. It definitely has a drop in quality after a certain point but the storyline in of itself was solid.\r\r\n Each character has good motivations. Definitely worth a watch. The ending is 50/50 depending on who you are as a person.",
    Tags: ["mystery,","justivevsmorality,","goodvsevil,","supernatural,","dark","intense"],
    Studio: "Madhouse",
    Platforms: ["Netflix","Hulu","Funimation","Amazon Video","hianime","9ananime","aniwave"],
    Trailer: "https://www.youtube.com/embed/NlJZ-YgAt-c"
    ,AniListId: 1535
    ,IdMal: 1535
    ,AniListScore: 84
    ,TitleEnglish: "Death Note"
    ,TitleRomaji: "DEATH NOTE"
    ,TitleNative: "DEATH NOTE"
  },
  {
    Title: "Charlotte",
    Genre: "Thriller/Supernatural",
    Rating: "9/10",
    image: "charlotte.png",
    Seasons: "1 season",
    Description: "A group of high school students with unstable supernatural abilities are brought together to prevent those powers from being exploited, only to uncover darker consequences tied to their existence.",
    Review: "I originally clicked on this anime because I thought it was going to be a cute romance story. Boy I was wrong.  It starts off as a lighthearted quicky school anime but quickly turns into a deep physiological bittersweet story. There is incredibly strong character development with the MC as the story progresses. Consequences are real and terribly harsh with the story getting increasingly intricate. Every character is well written and important to the overall story. The foreshadowing is clever and the title does serve a purpose. The only complaint I have about this anime is that the last episode was rushed for having such a good buildup.",
    Tags: ["existenialquestions,","drama,","supernatural,","juxtaposition,","emotional"],
    Studio: "P.A. Works",
    Platforms: ["Crunchyroll","Netflx","Amazon Video","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/kU5tGma7LaU"
    ,Top10Rank: 8
    ,AniListId: 20997
    ,IdMal: 28999
    ,AniListScore: 75
    ,AniListColor: "#f1c9a1"
    ,TitleRomaji: "Charlotte"
    ,TitleNative: "Charlotte(シャーロット)"
  },
  {
    Title: "Attack on Titan",
    Genre: "Mystery/Psychological",
    Rating: "15/10",
    image: "attack-on-titan.png",
    Seasons: "4 seasons, 1 movie",
    Description: "A boy wants to kill every titan after the death of his mom.",
    Review: "This is in my top 3 anime. I personally believe this is the greatest storyline/plot of all time. The amount of foreshadowing is actually insane when you watch it a 2nd -5th time. The characters are some of the best\r\r\n iv seen. Genuinely pulling some of the greatest themes/perspectives out of these characters. The score is something else on its own. It’s out of this world. I don’t think there was a single plot hole left in this anime. \r\r\nThe sheer amount of detail in the world building and titan descriptions is out of this world. I'm 100% a glazer of this anime but objectively this is one of the most well written animes in history.",
    Tags: ["action,","psycholgical,","warandfreedom,","identity,","emotional,","animation"],
    Studio: "Wit Studio, MAPPA",
    Platforms: ["Crunchyroll","Hulu","Amazon Video","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/n4Nj6Y_SNYI"
    ,Top10Rank: 3
    ,AniListId: 16498
    ,IdMal: 16498
    ,AniListScore: 85
    ,AniListColor: "#f1a143"
    ,TitleEnglish: "Attack on Titan"
    ,TitleRomaji: "Shingeki no Kyojin"
    ,TitleNative: "進撃の巨人"
  },
  {
    Title: "Classroom of the Elite",
    Genre: "Mystery/Psychological",
    Rating: "9/10",
    image: "classroom-of-the-elite.png",
    Seasons: "3 seasons",
    Description: "Students within an elite high school have to deal with an unusual curriculum where deception, betrayal, and violence are all behind the scenes.",
    Review: "Great premise and storyline. Characters are fleshed out over time especially the MC whose abilities and backstory are perfectly revealed as the anime goes on. \r\r\nFan service heavy in season 1 but the rest really picks up the plot. Overpowered MC.",
    Tags: ["psycholgical,","drama,","school,","strategy,","socialhierachy,","manipulation,","trust","op-mc"],
    Studio: "Lerche , Studio Bind",
    Platforms: ["Crunchyroll","Hulu","Amazon Video","Hidive","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/jOg75_8hAhM"
    ,AniListId: 98659
    ,IdMal: 35507
    ,AniListScore: 76
    ,AniListColor: "#bbf1a1"
    ,TitleEnglish: "Classroom of the Elite"
    ,TitleRomaji: "Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e"
    ,TitleNative: "ようこそ実力至上主義の教室へ"
  },
  {
    Title: "Re:ZERO − Starting Life in Another World",
    Genre: "Isekai/Fantasy",
    Rating: "10/10",
    image: "re-zero.png",
    Seasons: "3 seasons, 2 specials",
    Description: "A shut-in teenager is suddenly transported to a fantasy world where nothing is as kind as it first appears. Armed with a mysterious secret ability, he must navigate a dangerous world while trying to protect the people he grows close to.",
    Review: "When it comes to the greatest isekai anime. Re:ZERO is always in the conversation of having the best story and original adaptation. With that being said, one of the reasons the story is so good is because of how tragic it can be. The episodes are long, brutal, and showcase many emotional struggles. The MC is constantly beaten to the ground and yet, figures out a way to always find the strength to keep moving forward. There are occasional slow moments but overall, the story is immaculate. This isekai is unique to the hundreds of slop stories since the MC is never overpowered at any point in the story. It’s his intelligence and use of what’s given to him that make him so deadly. The anime teaches lessons most don’t dare approach.",
    Tags: ["thriller,","fantasy,","magic,","resilience,","tramua,","loyality,","dark,","action"],
    Studio: "White Fox",
    Platforms: ["Crunchyroll","Hulu","Apple TV","Amazon Video","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/Slz_rahWp6Y"
    ,Top10Rank: 2
    ,AniListId: 21355
    ,IdMal: 31240
    ,AniListScore: 81
    ,AniListColor: "#f150ae"
    ,TitleEnglish: "Re:ZERO -Starting Life in Another World-"
    ,TitleRomaji: "Re:Zero kara Hajimeru Isekai Seikatsu"
    ,TitleNative: "Re:ゼロから始める異世界生活"
  },
  {
    Title: "Failure Frame: I Became the Strongest and Annihilated Everything With Low Level Spells",
    Genre: "Isekai/Fantasy",
    Rating: "6.5/10",
    image: "failure-frame.png",
    Seasons: "1 season",
    Description: "A class of students is summoned to another world, but one boy is cast aside after being labeled with a weak magic ability—only to discover that his power grows in unexpected and dangerous ways.",
    Review: "The premise is that the MC is focused on revenge after getting thrown out of the hero’s party and while most revenge stories are satisfying, this one fails to deliver in a couple ways. It seems that the MC constantly changes his attitude around the anime leading you to believe he’s completely forgotten about getting revenge. The animation randomly switches to 3D which completely kills the Immersion and never looks good. Aside from that, the story just isn’t that good. However, if you are fan of watching overpowered MCs obliterate everyone then this is the show for you.",
    Tags: ["revenge,","powersystem,","3d"],
    Studio: "Seven Arcs",
    Platforms: ["Crunchyroll","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/1MylZpB5dIo"
    ,AniListId: 173694
    ,IdMal: 57892
    ,AniListScore: 63
    ,AniListColor: "#bb35e4"
    ,TitleEnglish: "Failure Frame: I Became the Strongest and Annihilated Everything with Low-Level Spells"
    ,TitleRomaji: "Hazure Waku no [Joutai Ijou Skill] de Saikyou ni Natta Ore ga Subete wo Juurin Suru made"
    ,TitleNative: "ハズレ枠の【状態異常スキル】で最強になった俺がすべてを蹂躙するまで"
  },
  {
    Title: "Farming Life in Another World",
    Genre: "Isekai/Fantasy",
    Rating: "7.5/10",
    image: "farming-life-in-another-world.png",
    Seasons: "1 season",
    Description: "A man is given a second chance at life after being unfairly treated in his first one.",
    Review: "This anime is the perfect way to relax after a long day. No stakes but pretty satisfying to watch the MCs farm and community grow. While it’s not groundbreaking in any way, the music did stand out as a highlight. \r\r\nNothing particularly bad or amazing it’s just a chill experience.",
    Tags: ["slice-of-life,","farming,","relaxing,","wholesome,","community"],
    Studio: "Zero-G",
    Platforms: ["HIDIVE","Amazon Video","hidive","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/hXIavkzdt4Y"
    ,AniListId: 146850
    ,IdMal: 51462
    ,AniListScore: 74
    ,AniListColor: "#e46b43"
    ,TitleEnglish: "Farming Life in Another World"
    ,TitleRomaji: "Isekai Nonbiri Nouka"
    ,TitleNative: "異世界のんびり農家"
  },
  {
    Title: "The Eminence in Shadow",
    Genre: "Isekai/Fantasy",
    Rating: "8.5/10",
    image: "eminence-in-shadow.png",
    Seasons: "2 seasons",
    Description: "A high school boy that dedicated his life to being the strongest meets an untimely end. He’s given a second chance.",
    Review: "Great satire anime where the MC is totally unaware that everyone around him genuinely believes in his motivations and actions. While it’s silly at times the goals of the MC are just as important to the anime and brought up consistently. \r\r\nThe serious moments are great. Moonlight Sonada being the MCs theme is iconic and perfectly matches the tone of the anime. Smooth animation, devolved side characters. One of my personal favorites if not my favorite anime.",
    Tags: ["op-mc,","comedy,","action,","power,","absurd,","secretsociety,","fanservice"],
    Studio: "Nexus, Studio Bind",
    Platforms: ["Hulu","Hidive","Amazon Video","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/L7LgAbGF-WY"
    ,Top10Rank: 1
    ,AniListId: 130298
    ,IdMal: 48316
    ,AniListScore: 81
    ,AniListColor: "#d61a1a"
    ,TitleEnglish: "The Eminence in Shadow"
    ,TitleRomaji: "Kage no Jitsuryokusha ni Naritakute!"
    ,TitleNative: "陰の実力者になりたくて！"
  },
  {
    Title: "The Water Magician",
    Genre: "Isekai/Fantasy",
    Rating: "8/10",
    image: "water-magician.png",
    Seasons: "1 season",
    Description: "Reborn into a magical new world with water magic and eternal youth, a man hopes for a peaceful life but is pulled into adventure and danger as he grows into his power and impacts the world around him.",
    Review: "This anime showcases gorgeous water painted backgrounds that are super unique. All the characters are great and have a place in the world with even background characters showing up consistently and developing personalities. Honestly, the only thing lacking with this anime is the animation. The storytelling, design, and context are all exceptional for a fantasy. Just wish the fight scenes add some more juice behind them.",
    Tags: ["action","combat","adventure","elves","magic","demons","backgrounds"],
    Studio: "Typhoon Graphics,  Wonderland",
    Platforms: ["Crunchyroll","Amazon Video","Apple TV","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/vQWodcG5x-I"
    ,AniListId: 186052
    ,IdMal: 60732
    ,AniListScore: 70
    ,AniListColor: "#43d6e4"
    ,TitleEnglish: "The Water Magician"
    ,TitleRomaji: "Mizu Zokusei no Mahou Tsukai"
    ,TitleNative: "水属性の魔法使い"
  },
  {
    Title: "My Status as an Assassin Obviously Exceeds the Hero’s",
    Genre: "Isekai/Fantasy",
    Rating: "7/10",
    image: "StatusAssassin.png",
    Seasons: "1 season",
    Description: "A quiet and overlooked student is transported to another world as an assassin, where his true abilities far surpass those of the chosen hero.",
    Review: "This anime features incredibly sharp and detailed character models that looked sick. While the animation looks strong in the opening shot of the first episode, the overall quality from the rest of the anime isn't up to par. The MC is definitely interesting in terms of his philosophy with others, but he does have some cringy moments as well. Didn't find the side characters particularly entertaining or unique, and the first season never felt like it went anywhere story wise. Now that may open up in the second season, but for now I can only describe this anime as lackluster.",
    Tags: ["assassin","op-mc","revenge","magic","dark-fantasty","anti-hero","power-system","strategy","combat","survival"],
    Studio: "Studio Sunrise",
    Platforms: ["Crunchyroll","Prime Video","Apple TV","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/gZQjg_YLxPw"
    ,AniListId: 186794
    ,IdMal: 61026
    ,AniListScore: 66
    ,AniListColor: "#4378e4"
    ,TitleEnglish: "My Status as an Assassin Obviously Exceeds the Hero’s"
    ,TitleRomaji: "Ansatsusha de Aru Ore no Status ga Yuusha yori mo Akiraka ni Tsuyoi no da ga"
    ,TitleNative: "暗殺者である俺のステータスが 勇者よりも明らかに強いのだが"
  },
  {
    Title: "Apocalypse Bringer Mynoghra: World Conquest Starts with the Civilization of Ruin",
    Genre: "Isekai/Fantasy",
    Rating: "7/10",
    image: "apocalypse-bringer.png",
    Seasons: "1 season",
    Description: "After dying young, Takuto is reborn in a game-like world with his demonic servant and seeks to build a civilization from ruin.",
    Review: "This anime has a solid premise that I think just could have been executed better. The animation is clearly lacking but not to the point where it ruins the anime. I will say that this can quickly turn from a fun filled comedy to serious merciless moments in a flash; it definitely surprised me in that aspect. The ending was pretty good and I'm excited for season 2.",
    Tags: ["nation-building,","stategy,","power-growth,","mid-animation"],
    Studio: "Maho Film",
    Platforms: ["Crunchyroll","Amazon Prime","Apple Tv","hianime","9animve","aniwave"],
    Trailer: "https://www.youtube.com/embed/OTL_4Fxwwtw"
    ,AniListId: 178433
    ,IdMal: 59130
    ,AniListScore: 66
    ,TitleEnglish: "Apocalypse Bringer Mynoghra: World Conquest Starts with the Civilization of Ruin"
    ,TitleRomaji: "Isekai Mokushiroku Mynoghra: Hametsu no Bunmei de Hajimeru Sekai Seifuku"
    ,TitleNative: "異世界黙示録マイノグーラ ～破滅の文明で始める世界征服～"
  },
  {
    Title: "The Angel Next Door Spoils Me Rotten",
    Genre: "Romance/Slice of Life",
    Rating: "10/10",
    image: "angel-next-door.png",
    Seasons: "1 season",
    Description: "A normal high school boy’s life changes when he offers his umbrella to a random girl sitting in the rain. To return the favor she offers help around his apartment leading to an incredibly cute romance.",
    Review: "My all-time favorite romance anime. A perfect setting and start leads to the most wholesome and sweet interactions in anime. Whenever I think of this story I genuinely start smiling and kicking my feet. The story is able to be interesting with realistic plot points and emotions. The side characters also exist and aren’t just forgotten the anime always has its focus on the two main characters.  Not to mention and completely unique premise I haven’t seen in a romance anime before. When it comes to feel goods, it’s hard to beat this.",
    Tags: ["school,","romcom,","wholesome,","caring,","personalgrowth"],
    Studio: "Project No. 9",
    Platforms: ["Crunchyroll","Amazon Prime Video","Apple TV","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/twfLsWdXcZI"
    ,Top10Rank: 4
    ,AniListId: 143338
    ,IdMal: 50739
    ,AniListScore: 78
    ,AniListColor: "#c9f1f1"
    ,TitleEnglish: "The Angel Next Door Spoils Me Rotten"
    ,TitleRomaji: "Otonari no Tenshi-sama ni Itsunomanika Dame Ningen ni Sareteita Ken"
    ,TitleNative: "お隣の天使様にいつの間にか駄目人間にされていた件"
  },
  {
    Title: "Alya Sometimes Hides Her Feelings In Russian",
    Genre: "Romance/Slice of Life",
    Rating: "9/10",
    image: "alya-sometimes-hides.png",
    Seasons: "1 season",
    Description: "A sharp-tongued high school girl secretly expresses her feelings toward her classmate in Russian, believing he can’t understand her—unaware that he hears every word.",
    Review: "This anime produced an amazing storyline for such a basic high school setting. The MC has a backstory which isn’t fully disclosed and is slowly explored as the season progresses. The interactions are unique between the two MCs since I haven’t seen this trope ever done in an anime before leading to great and cute moments. There is a bit of fan service but that doesn’t take away from how good this love story is. Highly recommend it.",
    Tags: ["fanservice,","school,","romcom,","drama,","student-council"],
    Studio: "Doga Kobo",
    Platforms: ["Crunchyroll","Amazon Video","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/CgacdWLGd0Y"
    ,AniListId: 162804
    ,IdMal: 54744
    ,AniListScore: 75
    ,AniListColor: "#d6ae78"
    ,TitleEnglish: "Alya Sometimes Hides Her Feelings in Russian"
    ,TitleRomaji: "Tokidoki Bosotto Russiago de Dereru Tonari no Alya-san"
    ,TitleNative: "時々ボソッとロシア語でデレる隣のアーリャさん"
  },
  {
    Title: "My Dress Up Darling",
    Genre: "Romance/Slice of Life",
    Rating: "9/10",
    image: "my-dress-up-darling.png",
    Seasons: "1 season",
    Description: "A shy boy devoted to doll-making unexpectedly bonds with a popular girl through their shared interest in cosplay, leading to personal growth and a slowly developing romance.",
    Review: "Cute and highly enjoyable romance anime with a unique premise. The characters are really well written and enjoyable to watch as they develop. Be warned this is definitely a fan service heavy anime. Pacing is done well and overall; it has a solid buildup. Incredibly sweet and bingeable in a single night.",
    Tags: ["fanservice,","cosplay,","wholesome,","school","romcom,"],
    Studio: "CloverWorks",
    Platforms: ["Crunchyroll","Amazon Video","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/8oveGY6h6T8"
    ,AniListId: 132405
    ,IdMal: 48736
    ,AniListScore: 80
    ,AniListColor: "#e46b5d"
    ,TitleEnglish: "My Dress-Up Darling"
    ,TitleRomaji: "Sono Bisque Doll wa Koi wo Suru"
    ,TitleNative: "その着せ替え人形は恋をする"
  },
  {
    Title: "The Girl I Like Forgot Her Glasses",
    Genre: "Romance/Slice of Life",
    Rating: "9/10",
    image: "the-girl-i-like-forgot-her-glasses.png",
    Seasons: "1 season",
    Description: "A high school girl who always forgets her glasses leads to cute and awkward moments with the boy that likes her.",
    Review: "This anime showcases incredibly unique and beautiful cinematography I haven’t seen in an anime before. There exists a slow natural buildup between the MCs that’s incredibly cute and wholesome to watch. While the gimmick may seem dumb there’s a good reason behind it and overall, it’s just a nice watch. The ending of season 1 leaves in a spot where season 2 can really shine.",
    Tags: ["romance,","romcom,","animation,","wholesome,","cute"],
    Studio: "GoHands",
    Platforms: ["Crunchyroll","Apple TV","Amazon Video","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/na8dVrRMj_8"
    ,AniListId: 160188
    ,IdMal: 54234
    ,AniListScore: 68
    ,AniListColor: "#e4d693"
    ,TitleEnglish: "The Girl I Like Forgot Her Glasses"
    ,TitleRomaji: "Suki na Ko ga Megane wo Wasureta"
    ,TitleNative: "好きな子がめがねを忘れた"
  },
  {
    Title: "The Dangers in My Heart",
    Genre: "Romance/Slice of Life",
    Rating: "9.5/10",
    image: "the-dangers-in-my-heart.png",
    Seasons: "2 seasons, 1 OVA",
    Description: "A lonely boy obsessed with dark thoughts starts falling for the cheerful girl who keeps noticing him.",
    Review: "Wholesome and emotionally grounded romance with a slow burn feel. The MC starts out pretty weird but quickly gets better. Pacing is good and rewarding. Couple dumb scenes but that comes out of most romance anime.\r\r\n One of the longer form romance animes currently out there.",
    Tags: ["school,","romcom,","wholesome,","personalgrowth,"],
    Studio: "Shin-Ei Animation",
    Platforms: ["Hidive","Apple TV","Amazon Video","Shudder","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/x-cTWEpQu_A"
    ,AniListId: 153152
    ,IdMal: 52578
    ,AniListScore: 81
    ,AniListColor: "#d6a150"
    ,TitleEnglish: "The Dangers in My Heart"
    ,TitleRomaji: "Boku no Kokoro no Yabai Yatsu"
    ,TitleNative: "僕の心のヤバイやつ"
  },
  {
    Title: "Kubo Won’t Let Me Be Invisible",
    Genre: "Romance / Slice of Life",
    Rating: "9/10",
    image: "kubo-wont-let-me-be-invisible.png",
    Seasons: "1 season",
    Description: "A quiet high school boy who fades into the background is repeatedly brought out of obscurity by a spirited classmate who refuses to let him stay invisible.",
    Review: "A very lovely and charming anime where the characters are entertaining; even all the side ones. I recommend binging this anime in a single night since it just makes you smile with all the in-class interactions between the MCs. There's nothing super great about it and nothing bad about this anime. As usual, the first season ended with a lot of potential for the second season, but nothing has been announced yet since the anime never got too popular.",
    Tags: ["school,","romcom,","teasing,","cute,","wholesome"],
    Studio: "Pine Jam",
    Platforms: ["Apple TV","Amazon Video","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/muy4GpTL2Bg"
    ,AniListId: 148969
    ,IdMal: 51815
    ,AniListScore: 74
    ,AniListColor: "#f1d6c9"
    ,TitleEnglish: "Kubo Won't Let Me Be Invisible"
    ,TitleRomaji: "Kubo-san wa Mob wo Yurusanai"
    ,TitleNative: "久保さんは僕を許さない"
  },
  {
    Title: "The Ice Guy and His Cool Female Colleague",
    Genre: "Romance / Slice of Life",
    Rating: "8.5/10",
    image: "the-ice-guy.png",
    Seasons: "1 season",
    Description: "A quiet office romance between a man descended from yuki-onna spirits and his calm, kind coworker, told through gentle everyday interactions.",
    Review: "An absolutely heartwarming and wholesome anime. Perfect to put on if you're looking for sweet interactions, well written characters, and a slow burn love over 12 episodes. Nothing overly stressful ever occurs and what else can I say. Definitely go give it a watch.",
    Tags: ["officeromance,","wholesome,","slowburn,","supernatural,","comfortanime,","romance"],
    Studio: "Liber, ZERO - G",
    Platforms: ["Crunchyroll","Amazon Prime Video","Apple TV","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/mgmHhWqoU54"
    ,AniListId: 151252
    ,IdMal: 52173
    ,AniListScore: 72
    ,AniListColor: "#28aee4"
    ,TitleEnglish: "The Ice Guy and His Cool Female Colleague"
    ,TitleRomaji: "Koori Zokusei Danshi to Cool na Douryou Joshi"
    ,TitleNative: "氷属性男子とクールな同僚女子"
  },
  {
    Title: "Our Dating Story: The Experienced You and The Inexperienced Me",
    Genre: "Romance/Drama",
    Rating: "7/10",
    image: "our-dating-story.png",
    Seasons: "1 season",
    Description: "A socially awkward high school boy unexpectedly begins dating one of the most popular girls in his class, forcing both of them to confront their insecurities, expectations, and very different experiences with love.",
    Review: "Not the most generic romance anime but it does get incredibly stupid at times. The first 7 episodes are interesting, but it gets a little dull after that. The ending comes back and ties everything up with a wholesome ending. If anything, the side character plots are just as intriguing if not more engaging than the main plot. Again, the ending is quite wholesome so if you’re looking for average binge worthy content, look no further.",
    Tags: ["school,","romcom,","drama,","fanservice"],
    Studio: "ENGI",
    Platforms: ["Crunchyroll","Apple TV","Amazon Video","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/HYfDGdnfbuY"
    ,AniListId: 154459
    ,IdMal: 52990
    ,AniListScore: 67
    ,AniListColor: "#d6ae6b"
    ,TitleEnglish: "Our Dating Story: The Experienced You and The Inexperienced Me"
    ,TitleRomaji: "Keikenzumi na Kimi to, Keiken Zero na Ore ga, Otsukiai suru Hanashi."
    ,TitleNative: "経験済みなキミと、経験ゼロなオレが、お付き合いする話。"
  },
  {
    Title: "More Than a Married Couple but Not Lovers",
    Genre: "Romance/Drama",
    Rating: "9/10",
    image: "more-than-a-married-couple.png",
    Seasons: "1 season",
    Description: "Two high school classmates are paired together in a mandatory “marriage practical” program where they must act like a married couple to earn the right to change partners, despite their vastly different personalities and initial reluctance; they slowly start falling for each other.",
    Review: "What starts out as a seemingly gooner anime quickly turns to sweet tension between 2 characters who initially hated each other. The tender moments between the MCs really make this anime for me. On a dime it can turn from a seemingly angry argument to real emotions. As the story progresses the tender moments only increase, and the characters slowly begin to change. I love the dynamic changes that occur throughout the story. By the end I fell in love with this anime and as time passed I only grew to like it more. One of my all-time favorite romances.",
    Tags: ["fanservice,","school,","livetogether,","romcom,","drama,","sweet,","wholesome"],
    Studio: "Studio MOTHER",
    Platforms: ["Crunchyroll","Apple TV","Amazon Prime Video","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/lfLS39jS-hQ"
    ,Top10Rank: 6
    ,AniListId: 141949
    ,IdMal: 50425
    ,AniListScore: 76
    ,AniListColor: "#d6e45d"
    ,TitleEnglish: "More than a Married Couple, but Not Lovers."
    ,TitleRomaji: "Fuufu Ijou, Koibito Miman."
    ,TitleNative: "夫婦以上、恋人未満。"
  },
  {
    Title: "Days with My Stepsister",
    Genre: "Romance/Drama",
    Rating: "10/10",
    image: "days-with-my-stepsister.png",
    Seasons: "1 season",
    Description: "A high school boy and girl, unrelated by blood, suddenly become step siblings. Now having to live\r\r\n to\r\r\ngether they carefully navigate their new relationship.",
    Review: "Do not let the title fool you. This is very different from all the other romance/slice of life animes out there. The pacing is realistic and patient. The MCs are intelligent and relatable. \r\r\nThey show genuine emotion, restraint, and introspection to their situation. The anime avoids cliches and handles complex emotions with subtlety. There’s a contemplative nature to every episode \r\r\nand I just haven’t seen this before in an anime. The background music is always soothing, almost meditative allowing the scenes to be fleshed out and contemplated.",
    Tags: ["drama,","romance,","thoughtprovoking,","fanservice,","personalgrowth,","soundtrack,","calming"],
    Studio: "Studio DEEN",
    Platforms: ["Crunchyroll","Amazon Video","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/_laWs_MfqN8"
    ,AniListId: 152681
    ,IdMal: 52481
    ,AniListScore: 73
    ,AniListColor: "#f1d6c9"
    ,TitleEnglish: "Days with My Stepsister"
    ,TitleRomaji: "Gimai Seikatsu"
    ,TitleNative: "義妹生活"
  },
  {
    Title: "My Stepmom’s Daughter Is My Ex",
    Genre: "Romance/Drama",
    Rating: "8.5/10",
    image: "my-stepmoms-daughter-is-my-ex.png",
    Seasons: "1 season",
    Description: "Two exes are forced to live in the same house after their parents remarry.",
    Review: "I liked how this anime slowly explored the goods/bads that come from a previous relationship and the growth it provides. It’s continently brought back up and is Important to the grand narrative.  \r\r\nNow being apart of a family also leads to interesting perspectives. The side characters don’t vanish and are actually present. The pacing is to quick in the first couple episodes but fixes itself. \r\r\nThe ending does leave some questions but that’s because the light novel has more to go. Overall it’s a thoughtful and enjoyable anime.",
    Tags: ["romcom,","fanservice,","school,","drama"],
    Studio: "Project No. 9",
    Platforms: ["Crunchyroll","Amazon Video","aniwave"],
    Trailer: "https://www.youtube.com/embed/TZ6GK37tDZQ"
    ,AniListId: 136934
    ,IdMal: 49470
    ,AniListScore: 66
    ,TitleEnglish: "My Stepmom's Daughter is My Ex"
    ,TitleRomaji: "Mamahaha no Tsurego ga Motokano datta"
    ,TitleNative: "継母の連れ子が元カノだった"
  },
  {
    Title: "Boarding School Juliet",
    Genre: "Romance/Drama",
    Rating: "9/10",
    image: "boarding-school-juliet.png",
    Seasons: "1 season",
    Description: "Within a prestigious boarding school there exist two rival factions: The white cats and black\r\r\n doggie\r\r\ns. What happens when the leader of the black cats falls in love with the other rival leader?",
    Review: "Honestly underrated comedy. This one had some funny moments that really made the anime. For the most part characters are solid and only a couple cringy moments exist. Definitely a feel-good watch.",
    Tags: ["secretrelationship,","rivalschools,","romcom,","comedy"],
    Studio: "LIDENFILMS",
    Platforms: ["Funimation","Amazon Video","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/TV_jnYsumck"
    ,AniListId: 101310
    ,IdMal: 37475
    ,AniListScore: 73
    ,AniListColor: "#e4a150"
    ,TitleEnglish: "Boarding School Juliet"
    ,TitleRomaji: "Kishuku Gakkou no Juliet"
    ,TitleNative: "寄宿学校のジュリエット"
  },
  {
    Title: "Watari-kun’s ****** Is About to Collapse",
    Genre: "Romance/Drama",
    Rating: "9/10",
    image: "Watari-kun.png",
    Seasons: "1 season",
    Description: "A responsible young man raising his little sister finds his carefully balanced life disrupted when a tragic childhood friend returns, forcing him to navigate complicated relationships, unresolved past feelings, and the emotional fallout that comes with them.",
    Review: "I have a lot to say. The first thing being: give this anime a chance. I made a mistake by going into this anime under the assumption that it was going to be a supernatural-heavy romance story. It’s not. There are no supernatural elements, and for the first half the plot isn’t overly serious. In fact, it’s actually quite terrible. There is a gross overuse of ecchi fan service that I can’t stand, as well as an infuriatingly dense, horny, and clueless main character who flip-flops on his emotions in a second. Couple that with a show that’s trying to be too many genres at once, and I was going to drop it. However, I kept watching. The second cour feels like a completely different show. The 26-episode length finally let it breathe, quickly shifting from retarded ecchi clichés to a real story. The main character underwent captivating development that completely changed the direction of the anime. It transcended a bait-and-switch trope to ask real questions about abandonment, obsession, forgiveness, and rebuilding after trauma. The other characters in this anime are great and really contribute to the story. There are some actual good comedic moments in the show as well that made me chuckle. The love triangle was dealt with nicely, and the anime went past the classic high school–only romance to show what thinking about a real future is like. In the end, the first 13 episodes weren’t useless but allowed a greater story to be told. All that was left was a heartfelt emotional triumph that’ll stick with me long after I write this review. To be really honest, this anime made me so sad because Im thinking about how I'm slowly going to forget all the wonderful details this anime had to offer. A messy start, but a journey worth every step. There will be no more seasons; this was a complete adaptation of the original manga.",
    Tags: ["seinen,","love-triangle,","school","relationships","emotional","character-growth,","coming-of-age,","complex,","fan-service","ecchi"],
    Studio: "Staple Entertainment",
    Platforms: ["Crunchyroll","Amazon Video","Apple TV","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/iPBqQWx-OX0"
    ,Top10Rank: 9
    ,AniListId: 169420
    ,IdMal: 56693
    ,AniListScore: 65
    ,AniListColor: "#c9e493"
    ,TitleEnglish: "Watari-kun's ****** Is about to Collapse"
    ,TitleRomaji: "Watari-kun no xx ga Houkai Sunzen"
    ,TitleNative: "渡くんの××が崩壊寸前"
  },
  {
    Title: "An Archdemon’s Dilemma: How to Love Your Elf Bride",
    Genre: "Fantasy/Romance",
    Rating: "9/10",
    image: "archdemons-dilemma.png",
    Seasons: "1 season",
    Description: "A surprising, cute and delightful anime that surprised in terms of quality in almost every way. The storyline: Top tier. Characters: Amazing. Magic System: Intricate and thoroughly explained. So many good moments from this anime where the characters shine. Several funny moments I wasn’t expecting made me laugh. Absolutely binge worthy.",
    Review: "Great storyline, animation is solid. Magic is explained well. Great character development. Pretty funny moments.",
    Tags: ["fantasy,","magic,","comedy,","heartwarming,","elves"],
    Studio: "Brain's Base",
    Platforms: ["Crunchyroll","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/52mVoy7ZYRY"
    ,AniListId: 156023
    ,IdMal: 53434
    ,AniListScore: 73
    ,AniListColor: "#50a1e4"
    ,TitleEnglish: "An Archdemon's Dilemma: How to Love Your Elf Bride"
    ,TitleRomaji: "Maou no Ore ga Dorei Elf wo Yome ni Shitanda ga, Dou Medereba Ii?"
    ,TitleNative: "魔王の俺が奴隷エルフを嫁にしたんだが、どう愛でればいい？"
  },
  {
    Title: "Rascal Does Not Dream of Bunny Girl Senpai",
    Genre: "Supernatural/Romance",
    Rating: "10/10",
    image: "bunny-girl-senpai.png",
    Seasons: "2 seasons, 3 movies",
    Description: "Puberty syndrome –  Abnormal experiences rumored on the internet to be caused by sensitivity and instability during adolescence. This year, Sakuta Azusagawa, a second-year student at a high school near Enoshima, meets several girls that are experiencing this “puberty syndrome.” For instance, he meets a wild bunny girl in the library. She turns out to be an actress on hiatus, Mai Sakurajima, who is also his senior at the school. For some reason, no one else can see this enchanting girl. How did she become invisible…?",
    Review: "About otherworldly syndromes, takes place in high school, one of the movies genuinely just had me sitting in the dark thinking about life. \r\r\nVery emotional, amazing characters, solid plot line. Highly recommend.",
    Tags: ["psycholgical,","supernatural,","romance,","drama,","identity,","complex,","emotionaltrauma,","healing"],
    Studio: "CloverWorks",
    Platforms: ["Crunchyroll","Hulu","Amazon Video","Netflix","hianime","9anime","aniwave (VPN)"],
    Trailer: "https://www.youtube.com/embed/4H_t9Dlk0mo"
    ,AniListId: 101291
    ,IdMal: 37450
    ,AniListScore: 81
    ,AniListColor: "#0d43f1"
    ,TitleEnglish: "Rascal Does Not Dream of Bunny Girl Senpai"
    ,TitleRomaji: "Seishun Buta Yarou wa Bunny Girl Senpai no Yume wo Minai"
    ,TitleNative: "青春ブタ野郎はバニーガール先輩の夢を見ない"
  },
  {
    Title: "The Magical Girl and the Evil Lieutenant Used to Be Archenemies",
    Genre: "Supernatural/Romance",
    Rating: "8/10",
    image: "the-magical-girl.png",
    Seasons: "1 season",
    Description: "The most evil man on the planet instantly falls in love with an enemy.",
    Review: "Sweet romcom. Episodes are really short so this is 100% an anime to binge in a single night. Wholesome with good characters and funny moments. Sadly, the author passed away and this anime will not be continued passed season 1. \r\r\nyou can read the light novel that slightly expands past the end of season 1 but thats it.",
    Tags: ["enimiestolovers,","romcom,","comedy,","magic"],
    Studio: "A-1 Pictures",
    Platforms: ["Crunchyroll","Apple TV","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/YwzmC_qBS7k"
    ,AniListId: 170938
    ,IdMal: 57217
    ,AniListScore: 74
    ,AniListColor: "#bbe4f1"
    ,TitleEnglish: "The Magical Girl and the Evil Lieutenant Used to Be Archenemies"
    ,TitleRomaji: "Katsute Mahou Shoujo to Aku wa Tekitai Shite Ita."
    ,TitleNative: "かつて魔法少女と悪は敵対していた。"
  },
  {
    Title: "Call of the Night",
    Genre: "Supernatural/Romance",
    Rating: "10/10",
    image: "call-of-the-night.png",
    Seasons: "2 seasons",
    Description: "A disillusioned boy wanders around the streets alone at night in search of meaning and stumbles upon an interesting girl with seveal secrets.",
    Review: "The stunning backgrounds and atmospheric artworks blew me away. This is genuinely one of the most gorgeous looking anime iv seems. Main characters are fantastic and the show balances some goofy charm with surprisingly \r\r\ndeep and introspective themes around love and connection. Easy to binge, wholesome with a touch of action. The gorgeous and vibrant visuals alone sets this one apart from the rest. One of my personal favorites.",
    Tags: ["vampires,","latenight,","slowburn,","atmospheric,","visuals,","nightlife,","romcom"],
    Studio: "LIDENFILMS",
    Platforms: ["Hidive","Disney Plus","Apple TV","Amazon Video","hianime","9anime","aniwave"],
    Trailer: "https://www.youtube.com/embed/anMP94lIFgs"
    ,Top10Rank: 5
    ,AniListId: 141391
    ,IdMal: 50346
    ,AniListScore: 79
    ,AniListColor: "#5d5de4"
    ,TitleEnglish: "Call of the Night"
    ,TitleRomaji: "Yofukashi no Uta"
    ,TitleNative: "よふかしのうた"
  },
  {
    Title: "The Foolish Angel Dances with the Devil",
    Genre: "Supernatural/Romance",
    Rating: "8/10",
    image: "foolish-angel.png",
    Seasons: "1 season",
    Description: "A demon infiltrating the human world falls for a stern angel — who secretly plots to reform him — leading to a chaotic celestial romance.",
    Review: "Personally, I feel like the MC started off really annoying and stupid. The plot was predictable and I really didn't think the anime was gonna go anywhere. Last 4–5 episodes did really well though and the animation surprised me. They balance the drama of school with the wars between heaven and hell pretty well in my opinion. Solid watch.",
    Tags: ["supernatural,","enimies-to-lovers,","angels,","demons,","school-life,","drama,","comedy"],
    Studio: "Children’s Playground Entertainment",
    Platforms: ["Crunchyroll","Amazon Prime","Apple TV","Amazon Video","hianime","9animve","aniwave"],
    Trailer: "https://www.youtube.com/embed/KC1Hz-4L1yY"
    ,AniListId: 164244
    ,IdMal: 55129
    ,AniListScore: 67
    ,AniListColor: "#5d93e4"
    ,TitleEnglish: "The Foolish Angel Dances with the Devil"
    ,TitleRomaji: "Oroka na Tenshi wa Akuma to Odoru"
    ,TitleNative: "愚かな天使は悪魔と踊る"
  },
  {
    Title: "Princess Mononoke",
    Genre: "Studio Ghibli",
    Rating: "8.9/10",
    image: "princess-mononoke.png",
    Seasons: "1 movie",
    Description: "A young warrior sets off west to find a cure for his curse that gives him unmatched strength.",
    Review: "Overall an incredibly well-crafted story where the movie never went in a predictable direction and kept me on my toes. The movie explored several ideas and themes including war and peace while asking difficult questions. The most interesting premise of the film was exploring the idea of being able to take both sides of a war. The only complaint  was that I felt the ending was a bit abrupt. Again, a beautiful story and I highly recommend it.",
    Tags: ["thoughtprovoking,","folklore,","warandpeace,","humananimalconflict"],
    Studio: "Studio Ghibli",
    Platforms: ["HBO Max","Amazon Prime Video","Apple TV","Fandango"],
    Trailer: "https://www.youtube.com/embed/4OiMOHRDs14"
    ,AniListId: 164
    ,IdMal: 164
    ,AniListScore: 85
    ,TitleEnglish: "Princess Mononoke"
    ,TitleRomaji: "Mononoke-hime"
    ,TitleNative: "もののけ姫"
  },
  {
    Title: "Hatsune Miku: Colorful Stage! A Miku Who Can’t Sing",
    Genre: "Musical/Idol",
    Rating: "5/10",
    image: "miku-movie.png",
    Seasons: "1 movie",
    Description: "A musical style movie set in a world where music is very popular.",
    Review: "Let me be clear: Musicals are not my area of expertise so there’s that. The movie itself I feel like had WAY too many main characters to keep track of. \r\r\nCertain plot points weren’t explained well. I can’t judge the music itself but I’m just not into this kinda thing hence the rating. Objectively it might be better but.",
    Tags: ["musical,","idol,","confusing,","miku,","domainexpansionsidk"],
    Studio: "Studio Colorido",
    Platforms: ["Blueray"],
    Trailer: "https://www.youtube.com/embed/3bD1dfiRMu4"
    ,AniListId: 179878
    ,IdMal: 59419
    ,AniListScore: 76
    ,AniListColor: "#43a1f1"
    ,TitleEnglish: "COLORFUL STAGE! The Movie: A Miku Who Can't Sing"
    ,TitleRomaji: "Project Sekai: Kowareta SEKAI to Utaenai MIKU"
    ,TitleNative: "プロジェクトセカイ 壊れたセカイと歌えないミク"
  },
];
